name: Go

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.22", "1.23"]
        os: 
          - ubuntu-latest
          - ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Build DB
        run: docker compose build

      - name: Start DB
        run: docker compose up -d

      - name: Run tests
        env:
          DB_HOST: localhost
        run: go test -v ./...
        
      - name: Stop DB
        if: always()
        run: docker compose down

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache: true

      - name: Build
        run: go build -v .